title: Anders Jändel
email: sviams@gmail.com
description: >-
  My random thoughts on good ways to generate business value with software
baseurl: "/blog"
url: "https://sviams.github.io"
twitter_username: anders_jandel
github_username:  sviams
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: thelehhman/texture
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass

texture:
  title: Anders Jändel
  tagline: Coding Architect
  style: black
  analytics_id: 'UA-149342947-1'
  showNav: true
  social_links:
    twitter: anders_jandel
    github: sviams
    linkedIn: in/andersjandel
    showPicker: true
